# Generated by Django 5.2.6 on 2025-10-22 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumprofilelink',
            name='most_important',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailTemplateContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(blank=True, null=True, related_name='email_templates', to='core.category')),
                ('sub_category', models.ManyToManyField(blank=True, null=True, related_name='email_templates', to='core.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='email-template-file/')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_attachments', to='core.emailtemplatecontent')),
            ],
        ),
    ]
