# Generated by Django 5.2.6 on 2025-10-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, choices=[('fiverr', 'fiverr'), ('freelancer', 'freelancer')], max_length=20, null=True)),
                ('url', models.URLField(max_length=255)),
            ],
        ),
    ]
