# Generated by Django 5.2.6 on 2025-10-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_premiumprofilelink_most_important_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplatecontent',
            name='for_proficiency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
