# Generated by Django 5.2.6 on 2025-10-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_premiumprofilelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidUsernameEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('status_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
