# Generated by Django 5.2.6 on 2025-10-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invalidusernameemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumprofilelink',
            name='is_scrapping',
            field=models.BooleanField(default=False),
        ),
    ]
