# Generated by Django 5.2.6 on 2025-10-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emailtemplatecontent_for_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplatecontent',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='email_templates', to='core.category'),
        ),
        migrations.AlterField(
            model_name='emailtemplatecontent',
            name='sub_category',
            field=models.ManyToManyField(blank=True, related_name='email_templates', to='core.subcategory'),
        ),
    ]
