# Generated by Django 5.2.6 on 2025-10-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_emailtemplatecontent_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplatecontent',
            name='category',
        ),
        migrations.RemoveField(
            model_name='emailtemplatecontent',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='EmailAttachment',
        ),
        migrations.DeleteModel(
            name='EmailTemplateContent',
        ),
    ]
