# Generated by Django 5.2.6 on 2025-11-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_emailtemplatecontent_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrevoEventLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_server_name', models.CharField(blank=True, max_length=50, null=True)),
                ('webhook_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
