# Generated by Django 5.2.6 on 2025-11-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_brevoeventlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOpenLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_server_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mail', models.JSONField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('open_count', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
