# Generated by Django 5.2.6 on 2025-11-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_emailopenlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailopenlog',
            name='mail',
        ),
        migrations.AddField(
            model_name='emailopenlog',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
