# Generated by Django 5.2.6 on 2025-11-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_emailopenlog_mail_emailopenlog_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailopenlog',
            name='open_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
