# Generated by Django 5.2.6 on 2025-11-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_emailopenlog_open_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEventLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(choices=[('brevo', 'Brevo'), ('maileroo', 'Maileroo')], default='brevo', max_length=25)),
                ('server_account', models.CharField(blank=True, max_length=50, null=True)),
                ('webhook_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
