# Generated by Django 5.2.6 on 2025-11-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_webhookeventlogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrevoEventLogs',
        ),
    ]
