# Generated by Django 5.2.6 on 2025-10-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
