# Generated by Django 5.2.6 on 2025-10-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0002_emailconfig_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='today_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='today_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='today_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
