# Generated by Django 5.2.6 on 2025-10-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0003_emailconfig_today_complete_emailconfig_today_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='daily_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
