# Generated by Django 5.2.6 on 2025-10-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0004_emailconfig_daily_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='server',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
