# Generated by Django 5.2.6 on 2025-10-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0005_emailconfig_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
