# Generated by Django 5.2.6 on 2025-10-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0006_emailconfig_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplatecontent',
            name='positive_rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplatecontent',
            name='response_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
