# Generated by Django 5.2.6 on 2025-10-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0007_emailtemplatecontent_positive_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplatecontent',
            name='type',
            field=models.CharField(choices=[('header_hook', 'Header Hook'), ('master', 'Master'), ('footer_hook', 'Footer Hook')], default='header_hook', max_length=25),
        ),
    ]
