# Generated by Django 5.2.6 on 2025-10-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0008_emailtemplatecontent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplatecontent',
            name='type',
            field=models.CharField(choices=[('header_hook', 'Header Hook'), ('master', 'Master'), ('footer_hook', 'Footer Hook'), ('signature_hook', 'Signature Hook')], default='header_hook', max_length=25),
        ),
    ]
