# Generated by Django 5.2.6 on 2025-10-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0009_alter_emailtemplatecontent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='type',
            field=models.CharField(blank=True, choices=[('smtp', 'Smtp'), ('api', 'Api')], default='smtp', max_length=25, null=True),
        ),
    ]
