# Generated by Django 5.2.6 on 2025-10-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0010_emailconfig_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='api_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
