# Generated by Django 5.2.6 on 2025-10-31 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0011_emailconfig_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfig',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='host_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='host_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='port',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
