# Generated by Django 5.2.6 on 2025-11-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0012_alter_emailconfig_email_alter_emailconfig_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplatecontent',
            name='type',
            field=models.CharField(choices=[('header_hook', 'Header Hook'), ('content_hook', 'Content Hook'), ('footer_hook', 'Footer Hook'), ('signature_hook', 'Signature Hook')], default='header_hook', max_length=25),
        ),
    ]
