# Generated by Django 5.2.6 on 2025-10-21 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiverrCompleteGigDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('details_type', models.CharField(choices=[('gig', 'gig'), ('profile', 'profile')], default='gig', max_length=10)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_scrapping', models.PositiveIntegerField(default=0)),
                ('collecting_email', models.PositiveIntegerField(default=0)),
                ('total_update', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FiverrReviewListWithEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('repeated', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=50)),
                ('price_tag', models.CharField(default='N/A', max_length=50)),
                ('proficiency', models.CharField(blank=True, choices=[('very low', 'very low'), ('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('very high', 'very high'), ('important', 'important'), ('most important', 'most important')], max_length=55, null=True)),
                ('time_text', models.CharField(default='N/A', max_length=55)),
                ('count', models.PositiveIntegerField(default=0)),
                ('review_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subcategory')),
            ],
        ),
    ]
