# Generated by Django 5.2.6 on 2025-09-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteGigDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('details_type', models.CharField(choices=[('gig', 'gig'), ('gig', 'gig')], default='gig', max_length=10)),
                ('url', models.CharField(max_length=255)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_update', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewListWithEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('repeated', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=50)),
                ('price_tag', models.CharField(default='N/A', max_length=50)),
                ('proficiency', models.CharField(choices=[('very low', 'very low'), ('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('very high', 'very high'), ('important', 'important'), ('most important', 'most important')], max_length=55)),
                ('time_text', models.CharField(default='N/A', max_length=55)),
                ('count', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=55, null=True)),
                ('review_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
