# Generated by Django 5.2.6 on 2025-10-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiverr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiverrreviewlistwithemail',
            name='price_tag',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
