# Generated by Django 5.2.6 on 2025-09-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiverr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlistwithemail',
            name='sub_category',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
