# Generated by Django 5.2.6 on 2025-10-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiverr', '0002_alter_fiverrreviewlistwithemail_price_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiverrreviewlistwithemail',
            name='price_tag',
            field=models.CharField(blank=True, default='N/A', max_length=255, null=True),
        ),
    ]
