# Generated by Django 5.2.6 on 2025-09-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiverr', '0002_reviewlistwithemail_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completegigdetails',
            name='details_type',
            field=models.CharField(choices=[('gig', 'gig'), ('profile', 'profile')], default='gig', max_length=10),
        ),
        migrations.AlterField(
            model_name='reviewlistwithemail',
            name='proficiency',
            field=models.CharField(blank=True, choices=[('very low', 'very low'), ('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('very high', 'very high'), ('important', 'important'), ('most important', 'most important')], max_length=55, null=True),
        ),
    ]
