# Generated by Django 5.2.6 on 2025-09-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiverr', '0003_alter_completegigdetails_details_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completegigdetails',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
