# Generated by Django 5.2.6 on 2025-10-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiverr', '0003_alter_fiverrreviewlistwithemail_price_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiverrreviewlistwithemail',
            name='follow_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fiverrreviewlistwithemail',
            name='follow_up_stage',
            field=models.CharField(blank=True, choices=[('stage_01', 'Stage 01'), ('stage_02', 'Stage 02'), ('stage_03', 'Stage 03'), ('stage_04', 'Stage 04'), ('stage_05', 'Stage 05'), ('stage_06', 'Stage 06')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiverrreviewlistwithemail',
            name='lead_stage',
            field=models.CharField(blank=True, choices=[('lost', 'Lost'), ('response', 'Response'), ('follow_up', 'Follow Up'), ('qualified', 'Qualified'), ('not_qualified', 'Not Qualified'), ('converted', 'Converted')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiverrreviewlistwithemail',
            name='most_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fiverrreviewlistwithemail',
            name='send_main',
            field=models.BooleanField(default=False),
        ),
    ]
