# Generated by Django 5.2.6 on 2025-09-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiverr', '0004_alter_completegigdetails_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='completegigdetails',
            name='collecting_email',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='completegigdetails',
            name='total_scrapping',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
