# Generated by Django 5.2.6 on 2025-10-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiverr', '0004_fiverrreviewlistwithemail_follow_up_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiverrreviewlistwithemail',
            old_name='send_main',
            new_name='send_mail',
        ),
    ]
