# Generated by Django 5.2.6 on 2025-09-30 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiverr', '0005_completegigdetails_collecting_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewlistwithemail',
            name='category',
        ),
        migrations.RemoveField(
            model_name='reviewlistwithemail',
            name='sub_category',
        ),
    ]
