# Generated by Django 5.2.6 on 2025-10-30 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiverr', '0005_rename_send_main_fiverrreviewlistwithemail_send_mail'),
        ('send_mail', '0009_alter_emailtemplatecontent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiverrreviewlistwithemail',
            name='last_event',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='fiverrreviewlistwithemail',
            name='last_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiverrreviewlistwithemail',
            name='last_mail_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_mails', to='send_mail.emailconfig'),
        ),
    ]
