# Generated by Django 5.2.6 on 2025-10-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiverr', '0006_fiverrreviewlistwithemail_last_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiverrreviewlistwithemail',
            name='last_provider_ts',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
