# Generated by Django 5.2.6 on 2025-09-30 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('fiverr', '0006_remove_reviewlistwithemail_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlistwithemail',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
        migrations.AddField(
            model_name='reviewlistwithemail',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subcategory'),
        ),
    ]
