# Generated by Django 5.2.6 on 2025-09-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiverr', '0007_reviewlistwithemail_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidUsernameEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
            ],
        ),
    ]
