# Generated by Django 5.2.6 on 2025-10-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiverr', '0007_fiverrreviewlistwithemail_last_provider_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiverrreviewlistwithemail',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fiverrreviewlistwithemail',
            name='deferred_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fiverrreviewlistwithemail',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiverrreviewlistwithemail',
            name='open_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fiverrreviewlistwithemail',
            name='send_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fiverrreviewlistwithemail',
            name='lead_stage',
            field=models.CharField(blank=True, choices=[('lost', 'Lost'), ('response', 'Response'), ('not_response', 'Not Response'), ('follow_up', 'Follow Up'), ('qualified', 'Qualified'), ('not_qualified', 'Not Qualified'), ('converted', 'Converted')], max_length=50, null=True),
        ),
    ]
