# Generated by Django 5.2.6 on 2025-09-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiverr', '0008_invalidusernameemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='invalidusernameemail',
            name='status_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
