# Generated by Django 5.2.6 on 2025-10-30 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiverr', '0008_fiverrreviewlistwithemail_click_count_and_more'),
        ('send_mail', '0009_alter_emailtemplatecontent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiverrreviewlistwithemail',
            name='last_mail_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiverr_send_mails', to='send_mail.emailconfig'),
        ),
    ]
