# Generated by Django 5.2.6 on 2025-10-09 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_premiumprofilelink'),
        ('fiverr', '0009_invalidusernameemail_status_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompleteGigDetails',
            new_name='FiverrCompleteGigDetails',
        ),
        migrations.RenameModel(
            old_name='InvalidUsernameEmail',
            new_name='FiverrInvalidUsernameEmail',
        ),
        migrations.RenameModel(
            old_name='ReviewListWithEmail',
            new_name='FiverrReviewListWithEmail',
        ),
    ]
