# Generated by Django 5.2.6 on 2025-10-09 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiverr', '0010_rename_completegigdetails_fiverrcompletegigdetails_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FiverrInvalidUsernameEmail',
        ),
    ]
