# Generated by Django 5.2.6 on 2025-10-09 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerr', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreelancerInvalidUsernameEmail',
        ),
    ]
