# Generated by Django 5.2.6 on 2025-10-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerr', '0002_freelancerreviewlistwithemail_follow_up_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancerreviewlistwithemail',
            old_name='send_main',
            new_name='send_mail',
        ),
    ]
