# Generated by Django 5.2.6 on 2025-10-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerr', '0003_rename_send_main_freelancerreviewlistwithemail_send_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerreviewlistwithemail',
            name='lead_stage',
            field=models.CharField(blank=True, choices=[('lost', 'Lost'), ('response', 'Response'), ('not_response', 'Not Response'), ('follow_up', 'Follow Up'), ('qualified', 'Qualified'), ('not_qualified', 'Not Qualified'), ('converted', 'Converted')], max_length=50, null=True),
        ),
    ]
