# Generated by Django 5.2.6 on 2025-10-30 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerr', '0004_alter_freelancerreviewlistwithemail_lead_stage'),
        ('send_mail', '0009_alter_emailtemplatecontent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerreviewlistwithemail',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freelancerreviewlistwithemail',
            name='deferred_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freelancerreviewlistwithemail',
            name='last_event',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='freelancerreviewlistwithemail',
            name='last_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancerreviewlistwithemail',
            name='last_mail_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancer_send_mails', to='send_mail.emailconfig'),
        ),
        migrations.AddField(
            model_name='freelancerreviewlistwithemail',
            name='last_provider_ts',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancerreviewlistwithemail',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancerreviewlistwithemail',
            name='open_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freelancerreviewlistwithemail',
            name='send_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
